version: '2'
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  collector-gateway:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector-gateway
    volumes:
      - ./collector-gateway.yaml:/etc/collector-gateway.yaml
    command: [ "--config=/etc/collector-gateway.yaml" ]
    ports:
      - "1888:1888" # pprof extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222" # Client connections
      - "6222:6222" # Cluster routes
      - "8222:8222" # HTTP monitoring
 
